Postman collection for 7.x
Ed-Fi-Exchange-OSS/Ed-Fi-Community-Postman-Collection pull request #5
Opened 2024-07-08 16:51 UTC by mjimdev

The pull request is related to the Sales force ticket (00002642)

2024-07-15 17:51 UTC, stevenarnold-ed-fi requested changes
Overall, looks good, just need to update to the latest (v7.2)

2024-07-15 17:51 UTC, stevenarnold-ed-fi commented on PostmanCollections3.x/EdFi_7_x.postman_environment.json
> +			"value": "https://api.ed-fi.org/v7.1/api/data/v3/",
@mjimdev Update this for v7.2 please

2024-07-18 22:02 UTC, mjimdev commented
@stevenarnold-ed-fi I renamed the files with your suggestion

2024-07-19 14:35 UTC, stevenarnold-ed-fi approved these changes

2024-07-19 14:35 UTC, merged